### ISSUE TITLE
Cannot destructure property `id` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by milobluebell** [Shopify/upload-to-release#3]
uses it with terminal console「Cannot destructure property `id` of 'undefined' or 'null'」，？

**Comment by mat-sienczyk** [comment]
Have the same, here is my workflow file:

`on:
  push:
    branches:
    - develop

name: Build and deploy Debug APK

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    - name: Upload to Release
      uses: Shopify/upload-to-release@1.0.0
      with:
        name: lsp_debug
        path: app/build/outputs/apk/debug/app-debug.apk
        repo-token: ${{ secrets.GITHUB_TOKEN }}`

**Comment by aissat** [comment]
Have the same

**Comment by lavoiesl** [comment]
Looks like it can happen when an asset is null. Unsure how that can happen, but I think https://github.com/Shopify/upload-to-release/pull/8 might fix it.
